# Generated by Django 6.0.3 on 2026-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('attendees', models.IntegerField(blank=True, default=0, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('major_tags', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
